
using System;
using LemonInc.Core.StateMachine.Interfaces;
using UnityEngine;
using System.Collections.Generic;

namespace LemonInc.Core.StateMachine
{
    // <auto-generated>
    //     This code was generated by a template.
    // </auto-generated>
    public partial class StateMachine
    {
        
                public StateGroup CreateGroup<T1, T2>()
            where T1 : IState
        where T2 : IState
        {
            var state1 = _nodes.GetValueOrDefault(typeof(T1));
        var state2 = _nodes.GetValueOrDefault(typeof(T2));

            if (state1 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T1).Name}");
            return null;
        }
        if (state2 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T2).Name}");
            return null;
        }

            var group = new StateGroup(this, state1.State, state2.State);
            _groups.Add(group);
            return group;
        }
                public StateGroup CreateGroup<T1, T2, T3>()
            where T1 : IState
        where T2 : IState
        where T3 : IState
        {
            var state1 = _nodes.GetValueOrDefault(typeof(T1));
        var state2 = _nodes.GetValueOrDefault(typeof(T2));
        var state3 = _nodes.GetValueOrDefault(typeof(T3));

            if (state1 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T1).Name}");
            return null;
        }
        if (state2 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T2).Name}");
            return null;
        }
        if (state3 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T3).Name}");
            return null;
        }

            var group = new StateGroup(this, state1.State, state2.State, state3.State);
            _groups.Add(group);
            return group;
        }
                public StateGroup CreateGroup<T1, T2, T3, T4>()
            where T1 : IState
        where T2 : IState
        where T3 : IState
        where T4 : IState
        {
            var state1 = _nodes.GetValueOrDefault(typeof(T1));
        var state2 = _nodes.GetValueOrDefault(typeof(T2));
        var state3 = _nodes.GetValueOrDefault(typeof(T3));
        var state4 = _nodes.GetValueOrDefault(typeof(T4));

            if (state1 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T1).Name}");
            return null;
        }
        if (state2 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T2).Name}");
            return null;
        }
        if (state3 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T3).Name}");
            return null;
        }
        if (state4 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T4).Name}");
            return null;
        }

            var group = new StateGroup(this, state1.State, state2.State, state3.State, state4.State);
            _groups.Add(group);
            return group;
        }
                public StateGroup CreateGroup<T1, T2, T3, T4, T5>()
            where T1 : IState
        where T2 : IState
        where T3 : IState
        where T4 : IState
        where T5 : IState
        {
            var state1 = _nodes.GetValueOrDefault(typeof(T1));
        var state2 = _nodes.GetValueOrDefault(typeof(T2));
        var state3 = _nodes.GetValueOrDefault(typeof(T3));
        var state4 = _nodes.GetValueOrDefault(typeof(T4));
        var state5 = _nodes.GetValueOrDefault(typeof(T5));

            if (state1 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T1).Name}");
            return null;
        }
        if (state2 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T2).Name}");
            return null;
        }
        if (state3 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T3).Name}");
            return null;
        }
        if (state4 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T4).Name}");
            return null;
        }
        if (state5 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T5).Name}");
            return null;
        }

            var group = new StateGroup(this, state1.State, state2.State, state3.State, state4.State, state5.State);
            _groups.Add(group);
            return group;
        }
                public StateGroup CreateGroup<T1, T2, T3, T4, T5, T6>()
            where T1 : IState
        where T2 : IState
        where T3 : IState
        where T4 : IState
        where T5 : IState
        where T6 : IState
        {
            var state1 = _nodes.GetValueOrDefault(typeof(T1));
        var state2 = _nodes.GetValueOrDefault(typeof(T2));
        var state3 = _nodes.GetValueOrDefault(typeof(T3));
        var state4 = _nodes.GetValueOrDefault(typeof(T4));
        var state5 = _nodes.GetValueOrDefault(typeof(T5));
        var state6 = _nodes.GetValueOrDefault(typeof(T6));

            if (state1 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T1).Name}");
            return null;
        }
        if (state2 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T2).Name}");
            return null;
        }
        if (state3 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T3).Name}");
            return null;
        }
        if (state4 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T4).Name}");
            return null;
        }
        if (state5 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T5).Name}");
            return null;
        }
        if (state6 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T6).Name}");
            return null;
        }

            var group = new StateGroup(this, state1.State, state2.State, state3.State, state4.State, state5.State, state6.State);
            _groups.Add(group);
            return group;
        }
                public StateGroup CreateGroup<T1, T2, T3, T4, T5, T6, T7>()
            where T1 : IState
        where T2 : IState
        where T3 : IState
        where T4 : IState
        where T5 : IState
        where T6 : IState
        where T7 : IState
        {
            var state1 = _nodes.GetValueOrDefault(typeof(T1));
        var state2 = _nodes.GetValueOrDefault(typeof(T2));
        var state3 = _nodes.GetValueOrDefault(typeof(T3));
        var state4 = _nodes.GetValueOrDefault(typeof(T4));
        var state5 = _nodes.GetValueOrDefault(typeof(T5));
        var state6 = _nodes.GetValueOrDefault(typeof(T6));
        var state7 = _nodes.GetValueOrDefault(typeof(T7));

            if (state1 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T1).Name}");
            return null;
        }
        if (state2 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T2).Name}");
            return null;
        }
        if (state3 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T3).Name}");
            return null;
        }
        if (state4 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T4).Name}");
            return null;
        }
        if (state5 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T5).Name}");
            return null;
        }
        if (state6 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T6).Name}");
            return null;
        }
        if (state7 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T7).Name}");
            return null;
        }

            var group = new StateGroup(this, state1.State, state2.State, state3.State, state4.State, state5.State, state6.State, state7.State);
            _groups.Add(group);
            return group;
        }
                public StateGroup CreateGroup<T1, T2, T3, T4, T5, T6, T7, T8>()
            where T1 : IState
        where T2 : IState
        where T3 : IState
        where T4 : IState
        where T5 : IState
        where T6 : IState
        where T7 : IState
        where T8 : IState
        {
            var state1 = _nodes.GetValueOrDefault(typeof(T1));
        var state2 = _nodes.GetValueOrDefault(typeof(T2));
        var state3 = _nodes.GetValueOrDefault(typeof(T3));
        var state4 = _nodes.GetValueOrDefault(typeof(T4));
        var state5 = _nodes.GetValueOrDefault(typeof(T5));
        var state6 = _nodes.GetValueOrDefault(typeof(T6));
        var state7 = _nodes.GetValueOrDefault(typeof(T7));
        var state8 = _nodes.GetValueOrDefault(typeof(T8));

            if (state1 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T1).Name}");
            return null;
        }
        if (state2 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T2).Name}");
            return null;
        }
        if (state3 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T3).Name}");
            return null;
        }
        if (state4 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T4).Name}");
            return null;
        }
        if (state5 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T5).Name}");
            return null;
        }
        if (state6 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T6).Name}");
            return null;
        }
        if (state7 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T7).Name}");
            return null;
        }
        if (state8 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T8).Name}");
            return null;
        }

            var group = new StateGroup(this, state1.State, state2.State, state3.State, state4.State, state5.State, state6.State, state7.State, state8.State);
            _groups.Add(group);
            return group;
        }
                public StateGroup CreateGroup<T1, T2, T3, T4, T5, T6, T7, T8, T9>()
            where T1 : IState
        where T2 : IState
        where T3 : IState
        where T4 : IState
        where T5 : IState
        where T6 : IState
        where T7 : IState
        where T8 : IState
        where T9 : IState
        {
            var state1 = _nodes.GetValueOrDefault(typeof(T1));
        var state2 = _nodes.GetValueOrDefault(typeof(T2));
        var state3 = _nodes.GetValueOrDefault(typeof(T3));
        var state4 = _nodes.GetValueOrDefault(typeof(T4));
        var state5 = _nodes.GetValueOrDefault(typeof(T5));
        var state6 = _nodes.GetValueOrDefault(typeof(T6));
        var state7 = _nodes.GetValueOrDefault(typeof(T7));
        var state8 = _nodes.GetValueOrDefault(typeof(T8));
        var state9 = _nodes.GetValueOrDefault(typeof(T9));

            if (state1 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T1).Name}");
            return null;
        }
        if (state2 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T2).Name}");
            return null;
        }
        if (state3 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T3).Name}");
            return null;
        }
        if (state4 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T4).Name}");
            return null;
        }
        if (state5 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T5).Name}");
            return null;
        }
        if (state6 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T6).Name}");
            return null;
        }
        if (state7 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T7).Name}");
            return null;
        }
        if (state8 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T8).Name}");
            return null;
        }
        if (state9 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T9).Name}");
            return null;
        }

            var group = new StateGroup(this, state1.State, state2.State, state3.State, state4.State, state5.State, state6.State, state7.State, state8.State, state9.State);
            _groups.Add(group);
            return group;
        }
                public StateGroup CreateGroup<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>()
            where T1 : IState
        where T2 : IState
        where T3 : IState
        where T4 : IState
        where T5 : IState
        where T6 : IState
        where T7 : IState
        where T8 : IState
        where T9 : IState
        where T10 : IState
        {
            var state1 = _nodes.GetValueOrDefault(typeof(T1));
        var state2 = _nodes.GetValueOrDefault(typeof(T2));
        var state3 = _nodes.GetValueOrDefault(typeof(T3));
        var state4 = _nodes.GetValueOrDefault(typeof(T4));
        var state5 = _nodes.GetValueOrDefault(typeof(T5));
        var state6 = _nodes.GetValueOrDefault(typeof(T6));
        var state7 = _nodes.GetValueOrDefault(typeof(T7));
        var state8 = _nodes.GetValueOrDefault(typeof(T8));
        var state9 = _nodes.GetValueOrDefault(typeof(T9));
        var state10 = _nodes.GetValueOrDefault(typeof(T10));

            if (state1 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T1).Name}");
            return null;
        }
        if (state2 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T2).Name}");
            return null;
        }
        if (state3 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T3).Name}");
            return null;
        }
        if (state4 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T4).Name}");
            return null;
        }
        if (state5 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T5).Name}");
            return null;
        }
        if (state6 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T6).Name}");
            return null;
        }
        if (state7 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T7).Name}");
            return null;
        }
        if (state8 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T8).Name}");
            return null;
        }
        if (state9 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T9).Name}");
            return null;
        }
        if (state10 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T10).Name}");
            return null;
        }

            var group = new StateGroup(this, state1.State, state2.State, state3.State, state4.State, state5.State, state6.State, state7.State, state8.State, state9.State, state10.State);
            _groups.Add(group);
            return group;
        }
                public StateGroup CreateGroup<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>()
            where T1 : IState
        where T2 : IState
        where T3 : IState
        where T4 : IState
        where T5 : IState
        where T6 : IState
        where T7 : IState
        where T8 : IState
        where T9 : IState
        where T10 : IState
        where T11 : IState
        {
            var state1 = _nodes.GetValueOrDefault(typeof(T1));
        var state2 = _nodes.GetValueOrDefault(typeof(T2));
        var state3 = _nodes.GetValueOrDefault(typeof(T3));
        var state4 = _nodes.GetValueOrDefault(typeof(T4));
        var state5 = _nodes.GetValueOrDefault(typeof(T5));
        var state6 = _nodes.GetValueOrDefault(typeof(T6));
        var state7 = _nodes.GetValueOrDefault(typeof(T7));
        var state8 = _nodes.GetValueOrDefault(typeof(T8));
        var state9 = _nodes.GetValueOrDefault(typeof(T9));
        var state10 = _nodes.GetValueOrDefault(typeof(T10));
        var state11 = _nodes.GetValueOrDefault(typeof(T11));

            if (state1 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T1).Name}");
            return null;
        }
        if (state2 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T2).Name}");
            return null;
        }
        if (state3 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T3).Name}");
            return null;
        }
        if (state4 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T4).Name}");
            return null;
        }
        if (state5 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T5).Name}");
            return null;
        }
        if (state6 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T6).Name}");
            return null;
        }
        if (state7 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T7).Name}");
            return null;
        }
        if (state8 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T8).Name}");
            return null;
        }
        if (state9 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T9).Name}");
            return null;
        }
        if (state10 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T10).Name}");
            return null;
        }
        if (state11 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T11).Name}");
            return null;
        }

            var group = new StateGroup(this, state1.State, state2.State, state3.State, state4.State, state5.State, state6.State, state7.State, state8.State, state9.State, state10.State, state11.State);
            _groups.Add(group);
            return group;
        }
                public StateGroup CreateGroup<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>()
            where T1 : IState
        where T2 : IState
        where T3 : IState
        where T4 : IState
        where T5 : IState
        where T6 : IState
        where T7 : IState
        where T8 : IState
        where T9 : IState
        where T10 : IState
        where T11 : IState
        where T12 : IState
        {
            var state1 = _nodes.GetValueOrDefault(typeof(T1));
        var state2 = _nodes.GetValueOrDefault(typeof(T2));
        var state3 = _nodes.GetValueOrDefault(typeof(T3));
        var state4 = _nodes.GetValueOrDefault(typeof(T4));
        var state5 = _nodes.GetValueOrDefault(typeof(T5));
        var state6 = _nodes.GetValueOrDefault(typeof(T6));
        var state7 = _nodes.GetValueOrDefault(typeof(T7));
        var state8 = _nodes.GetValueOrDefault(typeof(T8));
        var state9 = _nodes.GetValueOrDefault(typeof(T9));
        var state10 = _nodes.GetValueOrDefault(typeof(T10));
        var state11 = _nodes.GetValueOrDefault(typeof(T11));
        var state12 = _nodes.GetValueOrDefault(typeof(T12));

            if (state1 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T1).Name}");
            return null;
        }
        if (state2 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T2).Name}");
            return null;
        }
        if (state3 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T3).Name}");
            return null;
        }
        if (state4 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T4).Name}");
            return null;
        }
        if (state5 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T5).Name}");
            return null;
        }
        if (state6 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T6).Name}");
            return null;
        }
        if (state7 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T7).Name}");
            return null;
        }
        if (state8 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T8).Name}");
            return null;
        }
        if (state9 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T9).Name}");
            return null;
        }
        if (state10 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T10).Name}");
            return null;
        }
        if (state11 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T11).Name}");
            return null;
        }
        if (state12 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T12).Name}");
            return null;
        }

            var group = new StateGroup(this, state1.State, state2.State, state3.State, state4.State, state5.State, state6.State, state7.State, state8.State, state9.State, state10.State, state11.State, state12.State);
            _groups.Add(group);
            return group;
        }
                public StateGroup CreateGroup<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>()
            where T1 : IState
        where T2 : IState
        where T3 : IState
        where T4 : IState
        where T5 : IState
        where T6 : IState
        where T7 : IState
        where T8 : IState
        where T9 : IState
        where T10 : IState
        where T11 : IState
        where T12 : IState
        where T13 : IState
        {
            var state1 = _nodes.GetValueOrDefault(typeof(T1));
        var state2 = _nodes.GetValueOrDefault(typeof(T2));
        var state3 = _nodes.GetValueOrDefault(typeof(T3));
        var state4 = _nodes.GetValueOrDefault(typeof(T4));
        var state5 = _nodes.GetValueOrDefault(typeof(T5));
        var state6 = _nodes.GetValueOrDefault(typeof(T6));
        var state7 = _nodes.GetValueOrDefault(typeof(T7));
        var state8 = _nodes.GetValueOrDefault(typeof(T8));
        var state9 = _nodes.GetValueOrDefault(typeof(T9));
        var state10 = _nodes.GetValueOrDefault(typeof(T10));
        var state11 = _nodes.GetValueOrDefault(typeof(T11));
        var state12 = _nodes.GetValueOrDefault(typeof(T12));
        var state13 = _nodes.GetValueOrDefault(typeof(T13));

            if (state1 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T1).Name}");
            return null;
        }
        if (state2 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T2).Name}");
            return null;
        }
        if (state3 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T3).Name}");
            return null;
        }
        if (state4 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T4).Name}");
            return null;
        }
        if (state5 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T5).Name}");
            return null;
        }
        if (state6 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T6).Name}");
            return null;
        }
        if (state7 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T7).Name}");
            return null;
        }
        if (state8 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T8).Name}");
            return null;
        }
        if (state9 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T9).Name}");
            return null;
        }
        if (state10 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T10).Name}");
            return null;
        }
        if (state11 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T11).Name}");
            return null;
        }
        if (state12 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T12).Name}");
            return null;
        }
        if (state13 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T13).Name}");
            return null;
        }

            var group = new StateGroup(this, state1.State, state2.State, state3.State, state4.State, state5.State, state6.State, state7.State, state8.State, state9.State, state10.State, state11.State, state12.State, state13.State);
            _groups.Add(group);
            return group;
        }
                public StateGroup CreateGroup<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>()
            where T1 : IState
        where T2 : IState
        where T3 : IState
        where T4 : IState
        where T5 : IState
        where T6 : IState
        where T7 : IState
        where T8 : IState
        where T9 : IState
        where T10 : IState
        where T11 : IState
        where T12 : IState
        where T13 : IState
        where T14 : IState
        {
            var state1 = _nodes.GetValueOrDefault(typeof(T1));
        var state2 = _nodes.GetValueOrDefault(typeof(T2));
        var state3 = _nodes.GetValueOrDefault(typeof(T3));
        var state4 = _nodes.GetValueOrDefault(typeof(T4));
        var state5 = _nodes.GetValueOrDefault(typeof(T5));
        var state6 = _nodes.GetValueOrDefault(typeof(T6));
        var state7 = _nodes.GetValueOrDefault(typeof(T7));
        var state8 = _nodes.GetValueOrDefault(typeof(T8));
        var state9 = _nodes.GetValueOrDefault(typeof(T9));
        var state10 = _nodes.GetValueOrDefault(typeof(T10));
        var state11 = _nodes.GetValueOrDefault(typeof(T11));
        var state12 = _nodes.GetValueOrDefault(typeof(T12));
        var state13 = _nodes.GetValueOrDefault(typeof(T13));
        var state14 = _nodes.GetValueOrDefault(typeof(T14));

            if (state1 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T1).Name}");
            return null;
        }
        if (state2 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T2).Name}");
            return null;
        }
        if (state3 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T3).Name}");
            return null;
        }
        if (state4 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T4).Name}");
            return null;
        }
        if (state5 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T5).Name}");
            return null;
        }
        if (state6 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T6).Name}");
            return null;
        }
        if (state7 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T7).Name}");
            return null;
        }
        if (state8 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T8).Name}");
            return null;
        }
        if (state9 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T9).Name}");
            return null;
        }
        if (state10 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T10).Name}");
            return null;
        }
        if (state11 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T11).Name}");
            return null;
        }
        if (state12 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T12).Name}");
            return null;
        }
        if (state13 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T13).Name}");
            return null;
        }
        if (state14 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T14).Name}");
            return null;
        }

            var group = new StateGroup(this, state1.State, state2.State, state3.State, state4.State, state5.State, state6.State, state7.State, state8.State, state9.State, state10.State, state11.State, state12.State, state13.State, state14.State);
            _groups.Add(group);
            return group;
        }
                public StateGroup CreateGroup<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>()
            where T1 : IState
        where T2 : IState
        where T3 : IState
        where T4 : IState
        where T5 : IState
        where T6 : IState
        where T7 : IState
        where T8 : IState
        where T9 : IState
        where T10 : IState
        where T11 : IState
        where T12 : IState
        where T13 : IState
        where T14 : IState
        where T15 : IState
        {
            var state1 = _nodes.GetValueOrDefault(typeof(T1));
        var state2 = _nodes.GetValueOrDefault(typeof(T2));
        var state3 = _nodes.GetValueOrDefault(typeof(T3));
        var state4 = _nodes.GetValueOrDefault(typeof(T4));
        var state5 = _nodes.GetValueOrDefault(typeof(T5));
        var state6 = _nodes.GetValueOrDefault(typeof(T6));
        var state7 = _nodes.GetValueOrDefault(typeof(T7));
        var state8 = _nodes.GetValueOrDefault(typeof(T8));
        var state9 = _nodes.GetValueOrDefault(typeof(T9));
        var state10 = _nodes.GetValueOrDefault(typeof(T10));
        var state11 = _nodes.GetValueOrDefault(typeof(T11));
        var state12 = _nodes.GetValueOrDefault(typeof(T12));
        var state13 = _nodes.GetValueOrDefault(typeof(T13));
        var state14 = _nodes.GetValueOrDefault(typeof(T14));
        var state15 = _nodes.GetValueOrDefault(typeof(T15));

            if (state1 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T1).Name}");
            return null;
        }
        if (state2 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T2).Name}");
            return null;
        }
        if (state3 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T3).Name}");
            return null;
        }
        if (state4 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T4).Name}");
            return null;
        }
        if (state5 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T5).Name}");
            return null;
        }
        if (state6 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T6).Name}");
            return null;
        }
        if (state7 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T7).Name}");
            return null;
        }
        if (state8 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T8).Name}");
            return null;
        }
        if (state9 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T9).Name}");
            return null;
        }
        if (state10 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T10).Name}");
            return null;
        }
        if (state11 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T11).Name}");
            return null;
        }
        if (state12 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T12).Name}");
            return null;
        }
        if (state13 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T13).Name}");
            return null;
        }
        if (state14 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T14).Name}");
            return null;
        }
        if (state15 == null)
        {
            Debug.LogError($"Tried to register transition to unregistered state: {typeof(T15).Name}");
            return null;
        }

            var group = new StateGroup(this, state1.State, state2.State, state3.State, state4.State, state5.State, state6.State, state7.State, state8.State, state9.State, state10.State, state11.State, state12.State, state13.State, state14.State, state15.State);
            _groups.Add(group);
            return group;
        }
            }
}
