///
/// This code has been auto-generated by LemonInc.Tools.Databases
///

using LemonInc.Core.Utilities;
using LemonInc.Tools.Databases.Models;
using LemonInc.Editor.Utilities.Configuration;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace Databases
{
	public class CeciEstUnTestDatabase : Singleton<CeciEstUnTestDatabase>
	{
		private DatabaseData _data;
		public DatabaseData Data => _data ??= Resources.Load<DatabaseData>("Ceci est un test");

		public static class NewSection0
		{
			public static UnityEngine.Texture2D Action = (UnityEngine.Texture2D)CeciEstUnTestDatabase.Instance.Data
				.AssetDefinitions["8c2284b9-0c41-4441-aa1c-8d7bf6786298"].Data;

			/// <summary>
			/// Gets all assets from this section.
			/// </summary>
			/// <returns>An <see cref="IEnumerable{T}"/> of all assets.</returns>
			public static IEnumerable<T> All<T>()
				where T : UnityEngine.Object
			{
				var all = new UnityEngine.Object[1] { Action };
				return all.OfType<T>();
			}
		}

		public static class NewSection1
		{
			public static UnityEngine.Texture2D Action = (UnityEngine.Texture2D)CeciEstUnTestDatabase.Instance.Data
				.AssetDefinitions["60935394-c401-42df-b1bb-1dc14aefae31"].Data;

			/// <summary>
			/// Gets all assets from this section.
			/// </summary>
			/// <returns>An <see cref="IEnumerable{T}"/> of all assets.</returns>
			public static IEnumerable<T> All<T>()
				where T : UnityEngine.Object
			{
				var all = new UnityEngine.Object[1] { Action };
				return all.OfType<T>();
			}

			public static class NewSection0
			{
				public static UnityEngine.Texture2D Action = (UnityEngine.Texture2D)CeciEstUnTestDatabase.Instance.Data
					.AssetDefinitions["13fc7208-d239-401e-82ae-ee0c8a4b40cb"].Data;

				/// <summary>
				/// Gets all assets from this section.
				/// </summary>
				/// <returns>An <see cref="IEnumerable{T}"/> of all assets.</returns>
				public static IEnumerable<T> All<T>()
					where T : UnityEngine.Object
				{
					var all = new UnityEngine.Object[1] { Action };
					return all.OfType<T>();
				}

				public static class Ok
				{
					public static UnityEngine.Texture2D Action = (UnityEngine.Texture2D)CeciEstUnTestDatabase.Instance
						.Data.AssetDefinitions["a411d465-1f6f-4541-af9c-eee251e6a65a"].Data;

					/// <summary>
					/// Gets all assets from this section.
					/// </summary>
					/// <returns>An <see cref="IEnumerable{T}"/> of all assets.</returns>
					public static IEnumerable<T> All<T>()
						where T : UnityEngine.Object
					{
						var all = new UnityEngine.Object[1] { Action };
						return all.OfType<T>();
					}
				}

				public static class Ee
				{
					public static UnityEngine.Texture2D Action = (UnityEngine.Texture2D)CeciEstUnTestDatabase.Instance
						.Data.AssetDefinitions["0ef12b02-ceb7-48ed-93ae-cd5b81e5a2c2"].Data;

					/// <summary>
					/// Gets all assets from this section.
					/// </summary>
					/// <returns>An <see cref="IEnumerable{T}"/> of all assets.</returns>
					public static IEnumerable<T> All<T>()
						where T : UnityEngine.Object
					{
						var all = new UnityEngine.Object[1] { Action };
						return all.OfType<T>();
					}

					public static class NewSection0
					{
						public static UnityEngine.Texture2D Action = (UnityEngine.Texture2D)CeciEstUnTestDatabase
							.Instance.Data.AssetDefinitions["a4dc899b-11fa-488d-98ec-48e455dc1385"].Data;

						/// <summary>
						/// Gets all assets from this section.
						/// </summary>
						/// <returns>An <see cref="IEnumerable{T}"/> of all assets.</returns>
						public static IEnumerable<T> All<T>()
							where T : UnityEngine.Object
						{
							var all = new UnityEngine.Object[1] { Action };
							return all.OfType<T>();
						}
					}

					public static class Eee
					{
						public static UnityEngine.Texture2D Action = (UnityEngine.Texture2D)CeciEstUnTestDatabase
							.Instance.Data.AssetDefinitions["90a147b0-3703-40d2-a7c5-688a74bb25d4"].Data;

						/// <summary>
						/// Gets all assets from this section.
						/// </summary>
						/// <returns>An <see cref="IEnumerable{T}"/> of all assets.</returns>
						public static IEnumerable<T> All<T>()
							where T : UnityEngine.Object
						{
							var all = new UnityEngine.Object[1] { Action };
							return all.OfType<T>();
						}
					}
				}

				public static class NewSection2
				{
					public static UnityEngine.Texture2D Action = (UnityEngine.Texture2D)CeciEstUnTestDatabase.Instance
						.Data.AssetDefinitions["61cddc21-e7cf-4ef0-a262-06e8583b1114"].Data;

					/// <summary>
					/// Gets all assets from this section.
					/// </summary>
					/// <returns>An <see cref="IEnumerable{T}"/> of all assets.</returns>
					public static IEnumerable<T> All<T>()
						where T : UnityEngine.Object
					{
						var all = new UnityEngine.Object[1] { Action };
						return all.OfType<T>();
					}
				}
			}
		}

		public static class NewSection2
		{
			public static UnityEngine.Texture2D Action = (UnityEngine.Texture2D)CeciEstUnTestDatabase.Instance.Data
				.AssetDefinitions["2065fdb8-6dcd-49e0-ad97-7678a50e81e2"].Data;

			/// <summary>
			/// Gets all assets from this section.
			/// </summary>
			/// <returns>An <see cref="IEnumerable{T}"/> of all assets.</returns>
			public static IEnumerable<T> All<T>()
				where T : UnityEngine.Object
			{
				var all = new UnityEngine.Object[1] { Action };
				return all.OfType<T>();
			}
		}

	}


}

