///
/// This code has been auto-generated by LemonInc.Tools.Databases
///

using LemonInc.Core.Utilities;
using LemonInc.Tools.Databases.Models;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace Databases
{
	public class Main : Singleton<Main>
{
private DatabaseConfiguration _configInstance;
private DatabaseConfiguration Configuration => _configInstance ??= Resources.Load<DatabaseConfiguration>("Databases/DatabaseConfiguration");
public class Test
{
public static Assets.LemonInc.Test.SampleData DataB = (Assets.LemonInc.Test.SampleData)Instance.Configuration?.AssetDefinitions["15d4db23-e91e-48f5-a29e-019c4b90658d"].Data;
public static Assets.LemonInc.Test.SampleData NewSampleData = (Assets.LemonInc.Test.SampleData)Instance.Configuration?.AssetDefinitions["2addf8bb-f38a-4177-8a18-221ae5988d6e"].Data;
public static UnityEngine.GameObject Bullet = (UnityEngine.GameObject)Instance.Configuration?.AssetDefinitions["6a63fffb-004c-484b-86c3-ae47b70982c1"].Data;
public static UnityEngine.Sprite Angry = (UnityEngine.Sprite)Instance.Configuration?.AssetDefinitions["d2a16fdb-be87-4506-9443-1c964be538ec"].Data;

/// <summary>
/// Gets all assets from this section.
/// </summary>
/// <returns>An <see cref="IEnumerable{T}"/> of all assets.</returns>
public static IEnumerable<T> All<T>()
   where T : UnityEngine.Object
{
   var all = new UnityEngine.Object[4] { DataB, NewSampleData, Bullet, Angry };
   return all.OfType<T>();
}
}

}

public class NewDatabase1 : Singleton<NewDatabase1>
{
private DatabaseConfiguration _configInstance;
private DatabaseConfiguration Configuration => _configInstance ??= Resources.Load<DatabaseConfiguration>("Databases/DatabaseConfiguration");
}


}

