///
/// This code has been auto-generated by LemonInc.Tools.Databases
///

using LemonInc.Core.Utilities;
using LemonInc.Tools.Databases.Models;
using LemonInc.Editor.Utilities.Configuration;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace Databases
{
	public static class Main
{
public static class Test
{
public static UnityEngine.Texture2D Action = Resources.Load<UnityEngine.Texture2D>("Assets/LemonInc/Core/StateMachine/Editor/Resources/Action.png");
public static UnityEngine.Texture2D Banner = Resources.Load<UnityEngine.Texture2D>("Assets/LemonInc/Tools/Databases/Editor/Resources/Banner.png");
public static UnityEngine.Sprite Condition = Resources.Load<UnityEngine.Sprite>("Assets/LemonInc/Core/StateMachine/Editor/Resources/Condition.png");
public static UnityEditor.MonoScript AttributesExampleWindow = Resources.Load<UnityEditor.MonoScript>("Assets/Plugins/Sirenix/Assemblies/Sirenix.OdinInspector.Editor.dll");

/// <summary>
/// Gets all assets from this section.
/// </summary>
/// <returns>An <see cref="IEnumerable{T}"/> of all assets.</returns>
public static IEnumerable<T> All<T>()
   where T : UnityEngine.Object
{
   var all = new UnityEngine.Object[4] { Action, Banner, Condition, AttributesExampleWindow };
   return all.OfType<T>();
}
}

}


}

